name: learn_ai
description: "AI PracticeLab - An interactive, AI-driven learning assistant for programming."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  provider: ^6.1.2
  fl_chart: ^0.65.0
  path_provider: ^2.1.5
  logger: ^2.5.0
  uuid: ^4.5.1
  highlight: ^0.7.0
  flutter_code_editor: ^0.3.5
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.8
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - .env